/*
   Generated by EX4-TO-MQ4 decompiler V4.0.224.1 []
   Website: http://purebeam.biz
   E-mail : purebeam@gmail.com
*/
#property copyright "Copyright c 2008, TrendStuffer.com"
#property link      "http://www.trendstuffer.com/"

#property indicator_chart_window
#property indicator_buffers 1
#property indicator_color1 Red

double g_ibuf_76[];
double g_ibuf_80[];
double g_ibuf_84[];
extern int X = 0;
extern double Y = 0.0;
int gi_100 = 0;
int gi_104 = 0;

int init() {
   IndicatorBuffers(3);
   SetIndexBuffer(0, g_ibuf_76);
   SetIndexEmptyValue(1, 0);
   SetIndexBuffer(1, g_ibuf_80);
   SetIndexBuffer(2, g_ibuf_84);
   SetIndexEmptyValue(2, 0);
   return (0);
}

int start() {
   double ld_28;
   if (gi_100 == FALSE) {
      X /= 100;
      gi_100 = TRUE;
   }
   if (gi_104 == FALSE) {
      Y /= 1000.0;
      gi_104 = TRUE;
   }
   int li_0 = IndicatorCounted();
   if (li_0 < 0) return (-1);
   if (li_0 > 0) li_0--;
   int li_8 = Bars - 2 * X - 1;
   if (li_0 >= X) li_8 = Bars - li_0 - 1;
   if (li_8 < 0) li_8 = 0;
   for (int li_12 = li_8 + X + 1; li_12 >= 0; li_12--) g_ibuf_80[li_12] = iATR(NULL, 0, X, li_12);
   for (li_12 = li_8; li_12 >= 0; li_12--) g_ibuf_84[li_12] = iMAOnArray(g_ibuf_80, 0, X, 0, MODE_SMMA, li_12);
   for (int li_4 = li_8; li_4 >= 0; li_4--) {
      ld_28 = g_ibuf_84[li_4] * Y;
      if (Close[li_4] == g_ibuf_76[li_4 + 1]) g_ibuf_76[li_4] = g_ibuf_76[li_4 + 1];
      else {
         if (Close[li_4 + 1] <= g_ibuf_76[li_4 + 1] && Close[li_4] < g_ibuf_76[li_4 + 1]) g_ibuf_76[li_4] = MathMin(g_ibuf_76[li_4 + 1], Close[li_4] + ld_28);
         else {
            if (Close[li_4 + 1] >= g_ibuf_76[li_4 + 1] && Close[li_4] > g_ibuf_76[li_4 + 1]) g_ibuf_76[li_4] = MathMax(g_ibuf_76[li_4 + 1], Close[li_4] - ld_28);
            else {
               if (Close[li_4] > g_ibuf_76[li_4 + 1]) g_ibuf_76[li_4] = Close[li_4] - ld_28;
               else g_ibuf_76[li_4] = Close[li_4] + ld_28;
            }
         }
      }
   }
   return (0);
}
